# 作業目標:

    通過建立多層的神經網路, 了解權值矩陣更新

# 作業重點: 

3  層神經網路

通過增加更多的中間層，以對更多關係的組合進行建模

syn1 權值矩陣將隱層的組合輸出映射到最終結果，

而在更新 syn1 的同時，還需要更新 syn0 權值矩陣，

以從輸入資料中更好地產生這些組合

In [52]:
import numpy as np
 
# Sigmoid 函數可以將任何值都映射到一個位於 0 到  1 範圍內的值。通過它，我們可以將實數轉化為概率值
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])  
        
# define y for output dataset            
y = np.array([[1,1,0,0]]).T

In [53]:

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)
#亂數設定產生種子得到的權重初始化集仍是隨機分佈的，
#但每次開始訓練時，得到的權重初始集分佈都是完全一致的。
 
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,3)) - 1
# define syn1

iter = 0
#該神經網路權重矩陣的初始化操作。
#用 “syn0” 來代指 (即“輸入層-第一層隱層”間權重矩陣）
#用 “syn1” 來代指 (即“輸入層-第二層隱層”間權重矩陣）
syn1 = 2*np.random.random((3,1)) - 1


神經網路訓練
for 迴圈反覆運算式地多次執行訓練代碼，使得我們的網路能更好地擬合訓練集

In [54]:
print("l1.shape",l1.shape)
print("l0.shape",l1.shape)
print("syn0.shape",syn0.shape)
print("syn1.shape",syn1.shape)

l1.shape (4, 3)
l0.shape (4, 3)
syn0.shape (3, 3)
syn1.shape (3, 1)


In [55]:
for iter in range(10000):
    # forward propagation
    l0 = X #4*3
    l1 = nonlin(np.dot(l0,syn0)) #4*3 = 4*3 . 3*3
    l2 = nonlin(np.dot(l1,syn1)) #4*1 = 4*3 * 3*1
    #print("12.shape",l2.shape)
    '''
    新增
    l2_error 該值說明了神經網路預測時“丟失”的數目。
    l2_delta 該值為經確信度加權後的神經網路的誤差，除了確信誤差很小時，它近似等於預測誤差。
    '''
    l2_error = y -l2  #delta 3 #4*1
    l2_delta = l2_error+0  #delta3  #4*1
    #print("l2_delta.shape",l2_delta.shape)
    #print("l2_error.shape",l2_error.shape)
        
    # how much did we miss?
    #l1_error = y - l1
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    #l1_delta = l1_error * nonlin(l1,True)
    l1_delta = l2_delta* nonlin(l2,True)*syn1.T   #4*1 * 1*3 .  = 4*3
    # update weights
    
    syn1 = syn1 + np.dot(l1.T,l2_delta)  #theta 2   //3*4 * 4*1 = 3*1
    syn0 += np.dot(l0.T,l1_delta)  #3*4 . 4*3  = 3*3 
     # syn1 update weights
    
print("Output After Training:")
print(l2)
print("\n\n")
print(l1)

Output After Training:
[[9.99891983e-01]
 [9.99868678e-01]
 [5.86081616e-05]
 [1.36739011e-04]]



[[0.41504277 0.25824193 0.69730778]
 [0.34378694 0.11732364 0.59599745]
 [0.16078652 0.93058221 0.00769971]
 [0.12393383 0.83654891 0.00494443]]
