## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則話來觀察訓練情形。

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score

wine = datasets.load_wine()
boston = datasets.load_boston()

In [8]:
# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=4)

# 建立一個線性回歸模型
lasso = linear_model.Lasso(alpha=0.001)

# 將訓練資料丟進去模型訓練
lasso.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = lasso.predict(x_test)

In [9]:
# 印出各特徵對應的係數，可以看到許多係數都變成 0，Lasso Regression 的確可以做特徵選取
lasso.coef_

array([-1.15791752e-01,  4.71522626e-02,  6.82582501e-03,  3.21038693e+00,
       -1.63576832e+01,  3.88507202e+00, -1.11460239e-02, -1.53602292e+00,
        2.92392569e-01, -1.34271554e-02, -9.02961219e-01,  8.82369465e-03,
       -4.58252876e-01])

In [10]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 25.42


In [17]:
# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.1, random_state=4)

# 建立一個線性回歸模型
ridge = linear_model.Ridge(alpha=0.001)

# 將訓練資料丟進去模型訓練
ridge.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = ridge.predict(x_test)

In [18]:
# 印出各特徵對應的係數
ridge.coef_

array([-1.05066743e-01,  2.91916183e-02, -1.77875121e-01,  4.31536100e-02,
        1.01648722e-04,  1.49858782e-01, -3.70801570e-01, -2.59641790e-01,
        4.22876018e-02,  7.46213410e-02, -1.58463362e-01, -2.64600061e-01,
       -7.43808564e-04])

In [19]:
y_pred

array([ 1.58768937,  1.64857226, -0.47990698,  0.25774056,  0.54105033,
        2.03303932, -0.08369613,  0.87884412, -0.13016462,  1.04988717,
        1.09808195, -0.41944922,  1.85033026,  2.08422977,  0.07119406,
        0.99192519,  0.34809516,  0.93578119])